

#include "BindingCheck.h"
#include <fmt/os.h>
#include <fmt/core.h>

int main() {

    if (check_bindings()) {
        fmt::print(stderr, "Bindings check passed!\n");
        auto out = fmt::output_file("binding_check_stamp.h");
        out.print("// This file is generated by BindingCheckTool.cpp\n");
        out.print("#define BINDINGS_CHECK_PASSED 1\n");
        return 0; // Success
    } else {
        fmt::print(stderr, "Error: Bindings check failed!\n");
        return 1; // Failure
    }
}